version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/integration-tests"
    command: "wait-for-it.sh web:80 --recursive /integration-tests"
    depends_on:
      - web
  web:
    expose:
      - "80"
