version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/integration-tests"
      - "./screenshots:/screenshots"
    command: "wait-for-it.sh web:80 --recursive /integration-tests" #mocha goes here
    depends_on:
      - web
  web:
    image: tutum/hello-world
    expose:
      - "80"
